FROM node:22-alpine

WORKDIR /src/app

COPY  package.json package-lock.json turbo.json tsconfig.json ./

RUN npm install

RUN npm run db:genrate

COPY  apps/  ./

COPY  packages/  ./

RUN  npm run build

CMD ["npm" , "run" , "start-user-app"]
