FROM node:22-alpine

WORKDIR /src/app

COPY  package*.json  turbo.json tsconfig.json ./


COPY  apps  ./apps

COPY  packages  ./packages

RUN npm install --verbose

RUN npm run db:generate

RUN  npm run build

CMD ["npm" , "run" , "start-user-app"]
